### ISSUE TITLE
Whitelist/bypass mobile.twitter.com

### ISSUE THREAD

**Issue by fireattack** [ZusorCode/GoodTwitter#10]
Currently the UA change applies to all the twitter.com sub-domain.

This affects mobile.twitter.com as well, which will make it become a *very* old design.

The "new" mobile interface (without the addon) is actually exactly the same thing as the new main twitter.com interface (even before they actually switched).

So, if we whitelist/bypass mobile.twitter.com, people can temporarily use the new design when needed by just adding "mobile." to any link. This is particularly useful if you want to use, say, bookmark feature (you can just visit https://mobile.twitter.com/i/bookmarks), which is not available in the "old" mobile or desktop design.

**Comment by ZusorCode** [comment]
Fixed in f7bfe9b010b4848f3a07265e29668d6566ae6667
