### ISSUE TITLE
Can not like anything

### ISSUE THREAD

**Issue by Hampshirian** [ZusorCode/GoodTwitter#11]
When I click on the heart it turns red for a second then goes back to its original appearance. Also, FYI shift + reload does not allow videos to load for me.

**Comment by ZusorCode** [comment]
Sorry for not responding.
Is the issue still present? Have you tried the troubleshooting guide? https://github.com/ZusorCode/GoodTwitter/blob/master/troubleshooting.md

**Comment by Hampshirian** [comment]
I did before, but I can seem to use it at all anymore, even removing the app and reinstalling it. Maybe it's my Chromebook. The new Twitter is almost unusable on it.

Thanks,

Rebecca Gavin
 

Sent: Saturday, August 03, 2019 at 3:55 PM

**Comment by jezbel** [comment]
What worked to resolve most issues on the Good Twitter. Was, as someone else on another thread suggested, sign out of Twitter.  Then sign back in. It resolved most of the issues I was having. I have no idea why but it worked. For now.

**Comment by Hampshirian** [comment]
Thank you so much! I will definitely try that. What's up with Twitter leaving so many users stranded and frustrated?
 

Sent: Monday, August 05, 2019 at 1:25 AM

**Comment by ZusorCode** [comment]
I haven't seen this issue anywhere else, I think just signing out and back in should fix it
