### ISSUE TITLE
changes to feed of poster

### ISSUE THREAD

**Issue by petrysl** [ZusorCode/GoodTwitter#16]
if I open a thread the background feed changes to that of the poster, then I have to refresh two time to get back to my feed, but all of the tweets have changed.

**Comment by jezbel** [comment]
I think this is posted elsewhere. IF you sign out - and then sign back in to Twitter, it should take care of the issue. I don't know how long the fix lasts. But it's worked for many people.

**Comment by Chr1sFo** [comment]
> I think this is posted elsewhere. IF you sign out - and then sign back in to Twitter, it should take care of the issue. I don't know how long the fix lasts. But it's worked for many people.

Yes, worked for me. If you can't find the logout link, just add /logout to https://twitter.com/  i.e. https://twitter.com/logout
