### ISSUE TITLE
Good Twitter not working at all

### ISSUE THREAD

**Issue by Chr1sFo** [ZusorCode/GoodTwitter#17]
Was working fine yesterday.  Have tried logging out and back in.

**Comment by Xmetalfanx** [comment]
hmm I have seen the same issue at times (not for awhile mind you), and a logout and login again fixes it ... though this should sort-of doing the same thing ... make sure you delete the Twitter cookie after you logout (it still might be there) and then try logging in again

**Comment by maryellencg** [comment]
It's not working at all for me either, I've tried all the troubleshooting tips, including logging out, deleting the cookies, and logging back in.

**Comment by Chr1sFo** [comment]
Been working fine for me for the past month after following the tips.

**Comment by Chr1sFo** [comment]
> hmm I have seen the same issue at times (not for awhile mind you), and a logout and login again fixes it ... though this should sort-of doing the same thing ... make sure you delete the Twitter cookie after you logout (it still might be there) and then try logging in again

Thank you
