### ISSUE TITLE
New: Click a tweet to read thread and it jumps to that person's page

### ISSUE THREAD

**Issue by Zephmarie** [ZusorCode/GoodTwitter#24]
Until a couple days ago, I could click a tweet to read a thread and the main window would stay on main Twitter page. Now when I click a tweet to read a thread, the main window jumps to that person's page and I lose my place on main twitter. Anyone else experiencing this?

**Comment by maswartz** [comment]
This just started happening to me too!

**Comment by Zephmarie** [comment]
I don't remember that I did anything to fix it, but just as suddenly as it started happening, it stopped. During the time it was happening, if I wanted to read a thread, I would right click the time stamp to the right of the person's name and "open in new tab."
