### ISSUE TITLE
Loading profile pages instead of opening tweets over the notification page.

### ISSUE THREAD

**Issue by RailgunDesign** [ZusorCode/GoodTwitter#31]
Instead of tweets from notifications opening as an overlay over the current page, they instead load from the user's profile page. Same thing for "bubbled" tweets (likes, retweets, etc.). This is inconvenient, because I don't want to have to wait for the page to load, and then hit the back button every time I check a notification.
[Sorry for potato quality.](https://imgur.com/a/2zR3RQY)

**Comment by Penguinetta** [comment]
I have the same issue.

**Comment by maswartz** [comment]
This just started with me as well

**Comment by Penguinetta** [comment]
And now it's back to normal!  \o/

**Comment by maswartz** [comment]
Not here, it's still doing it. Should I uninstall and reinstall again?

**Comment by Penguinetta** [comment]
I've been setting up my new computer so I'm not sure if I did anything relevant.  Maybe log out of Twitter and see if it was just that?  Or reinstall your browser and the add-on?

**Comment by maswartz** [comment]
Logging out and in did it!

**Comment by Penguinetta** [comment]
Yay!  We are free!

**Comment by RailgunDesign** [comment]
I assume that's a solution, then. Although I would like to see a permanent fix. Closing.
