### ISSUE TITLE
pictures copy & pasting behaviour

### ISSUE THREAD

**Issue by paulsetchko** [ZusorCode/GoodTwitter#4]
the page creates a text input element when trying to insert a picture in a tweet.
before ctrl+v:
![image](https://user-images.githubusercontent.com/3169177/61851485-cb0b1b00-aebf-11e9-89d4-195c350c90f5.png)
after ctrl+v:
![image](https://user-images.githubusercontent.com/3169177/61851598-158c9780-aec0-11e9-844f-a2dbc8abd00a.png)

steps to reproduce:
1. Copy any picture into the clipboard manager
2. Launch the browser.
3. Open the twitter main page (https://twitter.com)
4. Click the "What's happening?" text input element
5. Press "ctrl+v" keys combination

I'm using Firefox 68.0 on Linux Mint Tessa with adblock and ghostery extensions that I've already tried disabling which didn't help, sadly.

**Comment by ReimarPB** [comment]
For now, before it gets fixed, you will have to right click and click "paste" to insert an image and if this happens, pressing any letter will remove the input field. I will look into this issue, though.

**Comment by paulsetchko** [comment]
thanks, it did the trick!

**Comment by ZusorCode** [comment]
So this bug is somewhat changed in d305e0b5c2724b2610d99d524cc919626b8816c3 as now images appear then disappear. What needs to be done is I need to figure out what type of content is in the clipboard. If it's an image let twitter handle the paste and if it's text cancel the propagation. I just haven't figured it out yet. Help is appreciated

**Comment by no-boot-device** [comment]
@ZusorCode [This](https://stackoverflow.com/a/6338207) might be useful, but if all else fails, I at one point wrote an addon that'd let you monkey patch Twitter's code.
