### ISSUE TITLE
Copy and paste 

### ISSUE THREAD

**Issue by S33qr** [ZusorCode/GoodTwitter#7]
I can't get copy and paste of text or URL's  to work in new tweet or replies. It works with images just not text.

**Comment by S33qr** [comment]
I should say I'm also using firefox 68.0.1 the ctrl+v pastes images just fine, but not text, Im also using Ublock Origin and CookiErazor, tried disabling both and didn't change anything even after CCleaner to clear FF cashe

**Comment by S33qr** [comment]
Also I use windows 10 Snipping tool for images to clipboard

**Comment by ZusorCode** [comment]
Got to about:addons and check the version of GoodTwitter you have. Make sure it's 1.8. The issue was fixed in that issue (although copy paste is not working for images

**Comment by S33qr** [comment]
Just got an update and **everything works, copy paste in original tweet and replies, text and pictures.** One thing though, when opening a picture from another tweet the picture is about 2 square inches by 2 1/2 inches on my 37 inch monitor. the new Twitter UI opened them almost as large as your firefox browser was open
