### ISSUE TITLE
Extension not active in Firefox containers

### ISSUE THREAD

**Issue by pascalchevrel** [ZusorCode/GoodTwitter#8]
Hi,

Great extension, thanks! The extension works fine in regular tabs but has no effect in containers tabs (a Firefox feature that allow having tabs with differente identies, see https://support.mozilla.org/en-US/kb/containers).

Cheers

**Comment by ZusorCode** [comment]
Do those containers even support extensions. I looked into it a bit and haven't found a way to make add-ons work in containers yet. If there is a possibility I will definitely look into it

**Comment by pascalchevrel** [comment]
Other extensions I use do work on container tabs yes.

**Comment by pascalchevrel** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Work_with_contextual_identities

**Comment by ZusorCode** [comment]
I couldn't figure out how to fix this, closing this for now unless someone else figures out how to fix this
