### ISSUE TITLE
GIFs/Videos not loading sometimes

### ISSUE THREAD

**Issue by ZusorCode** [ZusorCode/GoodTwitter#9]
I don't know how to fix this, help wanted

**Comment by Xmetalfanx** [comment]
I really am new to JS myself ... I was troubleshooting Videos playing fine and audio on those videos being really slow ... thought it was Umatrix (Addon) https://github.com/gorhill/uMatrix or one of its settings or filters misbehaving but after I saw this issue only affected Firefox and not in the new layout (when GoodTwitter is disabled), I just pinpoint it to be something in the addon doing it ...I will take a look to see if I can see what's happening  but there are TONS of people that may be able to fix this and do it much faster than I could

**Comment by ZusorCode** [comment]
Should be fixed in #23
